const contractAddress = "0xc816AC47C5Bb2D50DDd8Fc83CB95c561afE9f714"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the ";
const welcome_h3 = "Bount Town Bandits ";
const welcome_h4 = "NFT Project!!!";
const welcome_h2 = "Connect Your Wallet to Get Started";
const welcome_p = 'The Bounty Town Bandits offers a unique collection of 10,000 randomly generated Bandit NFTs. Each Bandit is designed from timeless thieves, outlaws, sheriffs, pirates, and 1920s gangsters; and, each Bandit has its own special gunslinger ability.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Whitelist Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "Whitelist is over. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Own Bandits!";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The BTB Community";
const button_public_mint = "Mint Your BTB NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
